language: rust

env:
  global:
    - CRATE_NAME=wagu
matrix:
  include:
    - rust: stable
      env: TARGET=x86_64-unknown-linux-musl
      addons:
        apt:
          packages:
          - libssl-dev
      after_success: 
        - |
          if [ "$TRAVIS_RUST_VERSION" == stable ]; then 
            cargo tarpaulin --all --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
          fi
    # deployments
    - env: DEPLOY=1 TARGET=x86_64-apple-darwin
      script: cargo build --release --target $TARGET
      os: osx
    - env: DEPLOY=1 TARGET=x86_64-unknown-linux-musl
      script: cargo build --release --target $TARGET
      addons:
        apt:
          packages:
          - musl-tools

script:
  - cargo build --verbose
  - RUST_BACKTRACE=1 cargo test --all --verbose
  - RUST_BACKTRACE=1 cargo test --all --verbose

before_deploy:
  - |
    name="wagu-$TRAVIS_TAG-$TARGET"
    mkdir $name
    cp target/$TARGET/release/sccache $name/
    cp README.md LICENSE $name/
    tar czvf $name.tar.gz $name
    echo -n $(shasum -ba 256 "$name.tar.gz" | cut -d " " -f 1) > $name.tar.gz.sha256


deploy:
  api_key:
    secure: LXMQT+GSw6ZtPA0Q+hnh6RSanesSWukR0NjstnMtXFx+gx9efFd9vyeuvyl46yUNvP1yXoe/U3fjwpH9cPWNQSHvmHU0onm+uulkmZ1lAHIuC7AwVQX4VY0yoDBZhrRJYBfy9GGEFvgYuvMHoEd57p98Jc3P7deZnOZbeqX1IMvFYh9nqa5LsJwMIKWWd/TiIR5+TByKbcy0FKQfoD5iGdlQgTT+XvqQ9Akg7qH1JCHxH+mVxp3anVtEPt6/Oll/E6geVet0qv4aHZUVgirnZgz0ucp+oCe8Dc/GZs3USKMaSg58AJkH5XQXbFnYj2+eVI0WLCww2UoY765Zbb9TmzQq/6r0ZGGtRTS6vsljAl2pJrzQYhNg3taAtbvGM0oy9kDyE+toMolzajyeSWtNdoXF/aGg9q6dddaAQ3A3R2mrNOZyC5JHRtrxWAOwrLHyvtstqPmvxYfrdtceb8T9tR8TDEarMIatEDj1+0CKvsg9LGzlr1nlcRHKHooiYpYigmv6tlROQ+bVWRfDNknDv4xVvffiKDsTFvMNBIi2xjjJsX7EQzgAgkmqJqBjGLbyYzdGLzW1AV7WjmwFMtfpdGALBysQ2YA27Khyr/OqBM91Qi5HMIYxE+oqjT5y+1eCiV6e3xY1zo74CcRB8fkL2jB46SoBoYw3B4lCbryT/u4=
  file_glob: true
  file:
    - wagu-$TRAVIS_TAG-$TARGET.tar.gz
    - wagu-$TRAVIS_TAG-$TARGET.tar.gz.sha256
  on:
    condition: $DEPLOY = 1
    tags: true
    repo: ArgusHQ/wagu-release-test
  provider: releases
  skip_cleanup: true

before_cache:
  - |
    if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
      if [[ "$TARGET" == x86_64-unknown-linux-musl ]]; then
            cargo install cargo-tarpaulin -f;
        else
            echo "not installing cargo-tarpaulin: not supported on $TARGET"
        fi
    fi

branches:
  only:
    # release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master

notifications:
  email:
    on_success: never