language: rust

sudo: required

rust:
  - stable
  - beta
  - nightly

addons:
  apt:
    packages:
      - libssl-dev

before_cache: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo install cargo-tarpaulin -f
  fi

script: cargo test --all

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo tarpaulin --out Xml --all
    bash <(curl -s https://codecov.io/bash)
  fi
  
