# Based on the "trust" template v0.1.2
# https://github.com/japaric/trust/tree/v0.1.2

dist: trusty
language: rust
services: docker
sudo: required

env:
  global:
    - CRATE_NAME=wagu
matrix:
  include:
    - rust: stable
      env: TARGET=x86_64-unknown-linux-musl
      addons:
        apt:
          packages:
          - libssl-dev
      after_success: 
        - |
          if [ "$TRAVIS_RUST_VERSION" == stable ]; then 
            cargo tarpaulin --all --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
          fi
    - env: TARGET=x86_64-unknown-linux-musl
      rust: beta
    - env: TARGET=x86_64-unknown-linux-musl
      rust: nightly
    - env: TARGET=x86_64-unknown-linux-gnu
    - env: TARGET=x86_64-unknown-linux-musl
    - env: TARGET=i686-apple-darwin
      os: osx
    - env: TARGET=x86_64-apple-darwin
      os: osx

before_install:
  - set -e
  - rustup self update

install:
  - sh scripts/install.sh
  - source ~/.cargo/env || true

script:
  - bash scripts/script.sh

after_script: set +e

before_deploy:
  - sh scripts/before_deploy.sh


deploy:
  # If the api_key ever needs to be updated: 
  # - Create a `public_repo` GitHub token. Go to: https://github.com/settings/tokens/new
  # - Encrypt it: `travis encrypt 0123456789012345678901234567890123456789
  # - Paste the output down here
  api_key:
    secure: "F6qQ6pJ8lwZag1p/xqpxXMT+rBB5cCFp2TzYxu0fx8w4b6ePs73lzYkjyTSLUn3Sj0+GyLBvNEgioDtfIpSIWEUSHmk7AF7t3s3cZMLEfhlDh0V8igStwjBDEmGlXEGaTeOWgwhsxoZhun8UOsBj1PNXONIicMAUyhDUnWjtjMgyc1zltRJUToSbYpoB7oHv+bTbRAX60ZVX5Ljx/ZTS1bAziqVX8teZwVyO0VQYRt4rUU8RAzjZfPScPj9ZApEKO76CRDIalDwZ4saEbqtGkLiWtZc5BynLlJ/oT8fPL05cbf1VgdKM6+ke059pEdLOE7RdIjrGPsgPeLhzNmnvPDBWOLvXp7jOSOjKxjzTu6yyCGdjDvNzaSXao8S0b30S2ydq2vpcRNRsAG6VkRJNL8V15RUqrbt9OBCyZRT/O0XfIWdDZ21fBjZxTi1jNC6s6p42SGTK7YEDseSLr6ipyK6EcaEkDZTra+UbmsUqSulGDN9AXFjVH4dKCa7t7qGgQNNFXyb7/4yvc4MzXgU9TxmTPGhfOCEIlXOzPswnI0if1NUtk4dGc7OGoYSNoL4TwTB0jedaTrYqFPFFYNhJdqts+zHgAC97VLavULFmdUfU39rkj9bA6RBIvxd43mq/g9BjBShzjTxip+2+GHKoPthFvVxNA5BVLoDskbvPmpg="
  file_glob: true
  file: $CRATE_NAME-$TRAVIS_TAG-$TARGET.*
  on:
    condition: $TRAVIS_RUST_VERSION = stable
    tags: true
    repo: ArgusHQ/wagu-release-test
  provider: releases
  skip_cleanup: true

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo
  - |
    if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
      if [ "$TARGET" == x86_64-unknown-linux-gnu ] || [ "$TARGET" == x86_64-unknown-linux-musl ]; then
            cargo install cargo-tarpaulin -f;
        else
            echo "not installing cargo-tarpaulin: not supported on $TARGET"
        fi
    fi

branches:
  only:
    # release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master

notifications:
  email:
    on_success: never