[package]
name = "wagu"
version = "0.5.0"
authors = ["Ali Mousa <amousa11@gmail.com>", "Collin Chin <collin@argus.observer>", "Raymond Chu <ray@argus.observer>"]
description = "Generate a wallet for any cryptocurrency. Pronounced like wagyu. Wagu is the wallet generation utility. Wagu allows users to generate wallets for the following cryptocurrencies: Bitcoin, Ethereum, Monero, Zcash (Transparent Addresses)"

homepage = "https://github.com/ArgusObserver/wagu"
repository = "https://github.com/ArgusObserver/wagu"

readme = "README.md"
license = "GPL-3.0"
categories = ["command-line-utilities"]
keywords = ["cryptocurrency", "blockchain", "bitcoin", "wallet", "ethereum"]
edition = "2018"


[dependencies]
arrayvec = "0.4.7"
base58 = "0.1"
clap = "~2.27.0"
digest = "0.7.5"
ed25519-dalek = "1.0.0-pre.1"
either = "1.5.0"
hex = "0.3.2"
hex-slice = "0.1.4"
lazy_static = "1.1.0"
rand = "0.6"
ripemd160 = "0.7"
safemem = "0.3.0"
secp256k1 = "0.11.1"
sha2 = "0.7"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tiny-keccak = "1.4"

[badges]
travis-ci = { repository = "ArgusObserver/wagu", branch = "master" }
