[package]
name = "ethereum"
version = "0.6.0"
authors = [
    "Collin Chin",
    "Raymond Chu",
    "Ali Mousa",
    "Howard Wu"
]
description = "A library for generating Ethereum wallets"
homepage = "https://github.com/ArgusHQ/wagu"
repository = "https://github.com/ArgusHQ/wagu"
categories = ["command-line-utilities"]
keywords = ["cryptocurrency", "blockchain", "bitcoin", "wallet", "ethereum"]
readme = "README.md"
license = "MIT/Apache-2.0"
edition = "2018"

[dependencies]
wagu-model = { path = "../model" }

base58 = { version = "0.1" }
bitvec = { version = "0.14.0" }
byteorder = { version = "1.2" }
hex = { version = "0.3.2" }
hmac = "0.7.0"
pbkdf2 = { version = "0.3.0", features=["parallel"], default-features = false }
rand = { version = "0.7" }
regex = "1"
secp256k1 = { version = "0.14.1" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.8"
tiny-keccak = "1.4"

[badges]
travis-ci = { repository = "ArgusHQ/wagu", branch = "master" }
