[package]
name = "ethereum"
version = "0.1.0"
authors = ["Ramond Chu <raychu86@gmail.com>"]

[dependencies]
rand = "0.5"
secp256k1 = "0.11.1"
tiny-keccak = "1.4"
hex = "0.3.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"