[package]
name = "monero"
version = "0.1.0"
authors = ["Collin Chin <collin@argus.observer>"]

[dependencies]
arrayvec = "0.4.7"
base58 = "0.1"
digest = "0.7.5"
either = "1.5.0"
lazy_static = "1.1.0"
openssl = "0.10.11"
rand = "0.5"
safemem = "0.3.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tiny-keccak = "1.0"
hex-slice = "0.1.4"

