[package]
name = "cli"
version = "0.3.0"
authors = ["Ali Mousa <amousa11@gmail.com>", "Raymond Chu <raychu86@gmail.com>"]

[dependencies]
bitcoin = { path = "../bitcoin" }
ethereum = { path = "../ethereum" }
zcash = { path = "../zcash" }
clap = "~2.27.0"
serde_json = "1.0"