[package]
name = "cli"
version = "0.2.0"
authors = ["Ali Mousa <amousa11@gmail.com>"]

[dependencies]
bitcoin = { path = "../bitcoin" }
zcash = { path = "../zcash" }
clap = "~2.27.0"
serde_json = "1.0"