[package]
name = "field_derive"
version = "0.3.0"
description = "Procedural macro library used to build custom prime field implementations"

[lib]
proc-macro = true

[dependencies]
num-bigint = "0.2"
num-traits = "0.2"
num-integer = "0.1"
proc-macro2 = "0.4"
quote = "0.6"
syn = "0.14"
