[package]
name = "bitcoin"
version = "0.2.0"
authors = ["Ali Mousa <amousa11@gmail.com>"]

[dependencies]
base58 = "0.1"
rand = "0.5"
ripemd160 = "0.7"
secp256k1 = "0.10.0"
sha2 = "0.7"
hex = "0.3.2"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"